<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Zend Framework Error Page</title>
	<link rel="stylesheet" href="/styles/main.css" />
	<script lang="javascript" src="/scripts/main.js"></script>
</head>
<body>
	<div id="welcome">
		<h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

		<h3>This is your project's main page</h3>

		<div id="more-information">
			<p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
			<p>
				Helpful Links: <br />
				<a href="http://framework.zend.com/">Zend Framework Website</a> |
				<a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
			</p>
		</div>
	</div>
</body>
</html>
